name: ${PROJECT_NAME}-init

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ${SHARED_DATA}/certbot/www/:/var/www/certbot/:rw
      - ${SHARED_DATA}/certbot/conf/:/etc/letsencrypt/:rw

  nginx:
    image: nginx:stable
    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf
    secrets:
      - certificate.crt
      - certificate.key
    volumes:
      - ${SHARED_DATA}/certbot/www/:/var/www/certbot/:ro
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443

configs:
  nginx:
    file: Nginx/nginx.le-init.conf

secrets:
  certificate.crt:
    file: ${SHARED_DATA}/certbot/live/${ROOT_DOMAIN}/fullchain.pem
  certificate.key:
    file: ${SHARED_DATA}/certbot/live/${ROOT_DOMAIN}/privkey.pem