# Compose file for initialising LetsEncrypt with XOSP. Designed to be used stand-alone
name: ${PROJECT_NAME}-init

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - type: volume
        source: shared
        target: /var/www/certbot
        volume:
          subpath: certbot/www
      - type: volume
        source: shared
        target: /etc/letsencrypt/
        volume:
          subpath: certbot/conf

  nginx:
    image: nginx:stable
    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - type: volume
        source: shared
        target: /var/www/certbot
        read_only: true
        volume:
          subpath: certbot/www
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443

configs:
  nginx:
    file: Nginx/nginx.le-init.conf
